export { JobDetLandingComponent } from './job-det-landing/job-det-landing.component'
export { JobDetInfoComponent } from './job-det-info/job-det-info.component'
export { JobDetCompanyComponent } from './job-det-company/job-det-company.component'
export { JobDetSubComponent } from './job-det-sub/job-det-sub.component'
export { VacancyDetailComponent } from './vacancy-detail/vacancy-detail.component'
